### ISSUE TITLE
[Nerdpack] Set up feature flag

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#102]
## Description
We want to ensure that, unless someone has the feature flag enabled, users will not be able to see the details for a Observability Pack.

The Developer Experience team might be setting this up.

## Acceptance Criteria
- [x] Create a staging feature flag for viewing Observability Pack details
- [x] Create a staging feature flag for installing an Observability Pack (displaying the button)
- [x] Create a production feature flag for viewing Observability Pack details
- [x] Create a production feature flag for installing an Observability Pack (displaying the button)
- [x] Create an EU production feature flag for viewing Observability Pack details
- [x] Create an EU production feature flag for installing an Observability Pack (displaying the button)
- [x] Add the Developer Enablement engineers to all feature flags

**Comment by rudouglas** [comment]
Created a new `DevEn` category in both Staging and Production with the following flags:

 - DevEn/view_observability_pack_details
 - DevEn/install_observability_pack

I added User Id's to the staging Whitelist because I could find this easily, for Production I set it to `Developer Enablement - Prod` account for now.

**Comment by rudouglas** [comment]
We will actually need to set this for EU production as well

**Comment by rudouglas** [comment]
EU account is `3244180`

**Comment by zstix** [comment]
🎉
