### ISSUE TITLE
[Nerdpack] Alerts & Runbooks

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#115]
## Description
As part of production readiness, we would like to set up a runbook to describe how to respond to issues and some alert conditions.

## Acceptance Criteria
- [x] Add an alert for JS errors for the details nerdlet
- [x] Add an alert for JS errors for the install nerdlet
- [x] Consider (and possibly implement) a synthetic monitor for both nerdlets
- [x] Create a runbook in the repository with links to the alert conditions and dashboards (#104)
- [x] Add some basic details to the runbook about how to troubleshoot

**Comment by zstix** [comment]
I created a page for our runbooks at `/wiki/Runbooks`. I'll add links to the list as we think of them to get us started.

**Comment by LizBaker** [comment]
We decided not to use a synthetics check for now. I do think it's worth deploying an error to double check on these during the bug bash since there is so little documentation on the instrumentation api I'm using on the platform.

I've also updated the runbook but it will need further updates if we change any nerdlet/launcher names since the feature flags will get updated
