### ISSUE TITLE
Additional Quickstarts creation and updates

### ISSUE THREAD

**Issue by rudouglas** [newrelic/newrelic-observability-packs#144]
## Description

This is a list of nits associated with the Integrations Epic.

### Repo
 - [x] There are 2 new packs related to Oracle Database (`OracleDB` and `Oracle`). Both point to the same documentation but have different summaries. Can these combined?
       *Yes, OracleDB is the most up to date name so we'll go with that*
 - [x] There are several integrations that don't have links to documentation, so we haven't made packs from these yet. We have to determine next steps for these
     - [x] ~~[Sybase](https://newrelic.com/integrations?query=sybase&tags=)~~ - `Coming Soon`
     - [x] ~~[CloudAMQP](https://newrelic.com/integrations?query=cloudam&tags=)~~ - `Coming Soon`
     - [x] ~~[Informix](https://newrelic.com/integrations?query=informix&tags=)~~ - `Coming Soon`
     - [x] [Pkg/Errors](https://newrelic.com/integrations?query=pkg&tags=) - This may cause issues with `/` as well
     - [x] [Websphere Liberty Profile](https://newrelic.com/integrations?query=liberty&tags=)
     - [x] [DNN Evoq](https://newrelic.com/integrations?query=evoq&tags=)

### Public Catalog
- [x] Check the `View Repo` button links to the nested sub-directory for new **_integration packs_**

### In-Product Nerdlet
- [x] Check the `View Repo` button links to the nested sub-directory for new **_integration packs_**

**Comment by jpvajda** [comment]
We are still waiting on the creation of this quickstarts.. @bradleycamacho did you have this on your radar to finish these up?

**Comment by bradleycamacho** [comment]
@jpvajda My apologies, I dropped the ball on this. Let me get back to you with a plan this afternoon for these specific packs.

 I can probably find some tangentially related docs for the last three, but I'm a bit at a loss on what to do for the "coming soon" ones. Let me stew on it for a bit!

**Comment by jpvajda** [comment]
@bradleycamacho Thanks!  I'd  say coming soon quickstarts are only added when there is someone able to contribute them. It's likely these were on a wish list someone was working on, but perhaps we can ask @jaesius about these as it could go on his targeted list of partners to pursue.

**Comment by bradleycamacho** [comment]
@jpvajda I've been trying to hunt these down, and this is what I have so far:

Websphere Liberty: https://docs.newrelic.com/docs/agents/java-agent/installation/include-java-agent-jvm-argument/#Installing_on_WebSphere_Liberty_Profile

PKG/Errors: https://docs.newrelic.com/docs/agents/go-agent/get-started/go-agent-compatibility-requirements/

DNN: https://docs.newrelic.com/docs/agents/net-agent/getting-started/introduction-new-relic-net/


I'm still at a loss for what to do with the `Coming Soon` integrations. I can't find any mention of them in our docs and any conversations I can find about them seem to be about the fact that we don't support them. I personally think we can just kill these off since they serve no purpose other than maybe SEO.

**Comment by jpvajda** [comment]
@bradleycamacho That works, if they come back up and their is interest in making them again, we can just create them then.
