### ISSUE TITLE
[Details Nerdlet] Markdown isn't rendering correctly in description

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#275]
### Issue

Markdown isn't rendering correctly in the description field 

### Steps to reproduce

go to a quickstart that has markdown in description
like[ dotnet  ](https://github.com/newrelic/newrelic-observability-packs/blob/main/packs/dotnet/dotnet/config.yml)
see description

### expected

markdown renders correctly

### screenshot
<img width="664" alt="Screen Shot 2021-09-18 at 8 48 17 AM" src="https://user-images.githubusercontent.com/1395158/133893125-24999d5f-c496-4f4f-b63c-614b81305ede.png">

**Comment by rudouglas** [comment]
I think the issue here is the way we are specifying `description` strings in the configuration yaml files. 

`description: >-` 
- `>` will "fold" the string when it's converted, which basically means all newlines are replaced with spaces. 
- `-` will tell it not to add a newline at the bottom

`description: |-` 
- `|` will keep the string "literal" so any newlines are kept
- `-` acts same as above

I'm not sure if we thought about this use-case in the beginning but this formatting will need to be changed in all quickstarts and templates

**Comment by rudouglas** [comment]
Altered the string to what it would be if the newlines were maintained and it renders correctly
<img width="1267" alt="Screenshot 2021-09-20 at 14 56 36" src="https://user-images.githubusercontent.com/17122543/134014837-7822f375-90ac-4891-b53e-102a9c7e1fd8.png">

**Comment by rudouglas** [comment]
https://github.com/newrelic/newrelic-observability-packs/pull/286
